<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Run multiple protractor specs in parallel</name>
   <tag></tag>
   <elementGuidId>997e6b2b-0a60-4ff1-8d32-f00de4c64c04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='node-259']/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;‹ Run multiple protractor specs in parallel&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8c0b758f-b82d-4030-8359-ec6940c86137</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/protractor-angularjs-tutorials/run-multiple-protractor-specs-in-parallel</value>
      <webElementGuid>bbca2ce6-d6cc-460d-b269-75dc4db903e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>‹ Run multiple protractor specs in parallel</value>
      <webElementGuid>c1e64c57-0f31-46dd-9ec6-eca485864eb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>‹ Run multiple protractor specs in parallel</value>
      <webElementGuid>70d83b83-94da-47e3-87b0-b47683387a55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;node-259&quot;)/ul[@class=&quot;flippy&quot;]/li[@class=&quot;prev&quot;]/a[1]</value>
      <webElementGuid>11b37240-5cad-4526-a523-11117d7a6827</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='node-259']/ul/li/a</value>
      <webElementGuid>2be92f8e-2e14-4732-ae3d-7dfb3dd80cca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'‹ Run multiple protractor specs in parallel')]</value>
      <webElementGuid>c518417d-52c9-44ec-9fbe-fd52f2173eab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/protractor-angularjs-tutorials/run-multiple-protractor-specs-in-parallel')]</value>
      <webElementGuid>238ad2c6-bdb6-41ed-8607-1bcc66c89935</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article/ul/li/a</value>
      <webElementGuid>ae2d5b10-6ca2-4f9d-8e95-89c41259dacf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/protractor-angularjs-tutorials/run-multiple-protractor-specs-in-parallel' and @title = '‹ Run multiple protractor specs in parallel' and (text() = '‹ Run multiple protractor specs in parallel' or . = '‹ Run multiple protractor specs in parallel')]</value>
      <webElementGuid>f6948cfa-571e-4d9e-8947-8d90faace080</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
