<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Run tests in parallel with pytest</name>
   <tag></tag>
   <elementGuidId>01a5e6f4-3f67-46e9-b229-4eba9458a279</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='node-259']/header/h2/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h2 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6a2deef6-a85f-4e94-ae8f-def9f20cdc48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/python/pytest-run-webdriver-tests-in-parallel</value>
      <webElementGuid>e2c56918-33f9-461f-849a-01abbefa648e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Run tests in parallel with pytest</value>
      <webElementGuid>b1a07953-21e5-46af-b10f-70c3f9ab7671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;node-259&quot;)/header[1]/h2[1]/a[1]</value>
      <webElementGuid>9ce18596-02e6-40cc-ae1f-31b04f2f21f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='node-259']/header/h2/a</value>
      <webElementGuid>97bc4081-45c5-489b-baa1-26d97c5225c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Run tests in parallel with pytest')]</value>
      <webElementGuid>ca2a2028-07a8-4de8-8192-b44cfefcbbc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/python/pytest-run-webdriver-tests-in-parallel')]</value>
      <webElementGuid>a571d9b7-e74b-47af-a397-cb7126f868a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2/a</value>
      <webElementGuid>a8a7fa09-8693-4f58-881b-90477f347906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/python/pytest-run-webdriver-tests-in-parallel' and (text() = 'Run tests in parallel with pytest' or . = 'Run tests in parallel with pytest')]</value>
      <webElementGuid>58a1f544-1613-4514-ba8c-d441cbc48c87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
