<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_ecbiz312.inmotionhosting.com</name>
   <tag></tag>
   <elementGuidId>b94cee34-cca3-480c-a6e9-c74b348464eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h2</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>8f54e807-510e-4de4-bce0-4c344abdcfe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ecbiz312.inmotionhosting.com</value>
      <webElementGuid>82a6b8ee-f5e5-4994-b6ce-2bae9c8476c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/center[1]/font[1]/font[1]/strong[1]/h2[1]</value>
      <webElementGuid>d86c9a91-7b36-4075-80c3-16ed434664cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>075559f2-dfb5-4222-85f8-e28235cd0cb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'ecbiz312.inmotionhosting.com' or . = 'ecbiz312.inmotionhosting.com')]</value>
      <webElementGuid>50f278fd-4f6d-43c6-828e-ad3951a220f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
