<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_httpautomationpractice.comindex.php</name>
   <tag></tag>
   <elementGuidId>b54a999c-2580-49bc-be16-7aad09471bfd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h3[@id='_2-httpautomationpracticecomindexphp-1']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#_2-httpautomationpracticecomindexphp-1 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>211fd17b-aee7-4030-be1d-f0c6f3b568b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://automationpractice.com/index.php</value>
      <webElementGuid>ff5a1894-6dcd-4599-a499-4f67f49dffab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>6d41f26d-b04f-455e-b629-edd78c3c52bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>http://automationpractice.com/index.php</value>
      <webElementGuid>93704cf7-05f4-439e-b383-64affd144eaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_2-httpautomationpracticecomindexphp-1&quot;)/a[1]</value>
      <webElementGuid>700f356c-a80e-4e2c-b04e-116fc5f3541d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//h3[@id='_2-httpautomationpracticecomindexphp-1']/a</value>
      <webElementGuid>d35cc60d-df0e-45be-b391-025522b2e5ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'http://automationpractice.com/index.php')]</value>
      <webElementGuid>d0e2df5e-dc9d-470f-bb51-6b2748e39880</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://automationpractice.com/index.php']</value>
      <webElementGuid>c1d94bee-d102-43a3-9620-60cee32c093d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3[2]/a</value>
      <webElementGuid>acec9d79-89bb-44cf-a4d1-77f5163fffe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://automationpractice.com/index.php' and (text() = 'http://automationpractice.com/index.php' or . = 'http://automationpractice.com/index.php')]</value>
      <webElementGuid>24cd13f4-08f8-49a6-8e8f-901ea441dc71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
