name: Android Test

on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: actions/setup-node@v2
        with:
         node-version: '12'
      - run: |
              npm install -g appium@v1.20.2
              appium -v
              appium &>/dev/null &
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      
      - name: Build SampleApplication
        run: ./gradlew --no-daemon build
