name: Android Test

on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      - name: Cài đặt Gradle
        uses: gradle/gradle-build-action@v2
      - name: Install android-emulator-runner
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          package-name: "system-images;android-30;google_apis;x86"
          emulator-version: 30
      - name: Start Android Emulator
        run: emulator -avd ${{ runner.os }}-emu -no-audio -no-window
        
             
      - name: Get device ID
        if: always()
        run: adb devices
        id: get-device-id
