name: Android Test

on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Setup Android SDK
        # Thay đổi đường dẫn cho phù hợp
        run: |
          Set-ExecutionPolicy RemoteSigned
          $env:ANDROID_HOME="C:\Android\sdk"
          $env:PATH="$env:PATH;$env:ANDROID_HOME\platform-tools"

      - name: Chạy test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 23
          script: ./gradlew connectedCheck

