name: Android Test

on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install adb
        run: sudo apt-get install -y adb

      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          license: accept
          headless: true
          emulator-flags: '-no-snapshot-save -no-boot-anim'
        id: emulator

      - name: Get device ID
        run: echo "deviceId=${{ steps.emulator.outputs.device-id }}" >> $GITHUB_ENV

      - name: Show device ID
        run: echo "Device ID is ${{ env.deviceId }}"

      - name: Terminate Emulator
        run: |
          sleep 90  # Thời gian chờ 30 giây
          adb -s ${{ steps.emulator.outputs.device-id }} emu kill
