name: Genymotion Cloud SaaS 

on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Start Genymotion Cloud SaaS instance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10.11"

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Start Genymotion Cloud SaaS instance
        uses:  genymobile/genymotion-saas-github-action@v0.4
        with:
          email: ${{ secrets.GMSAAS_EMAIL }}
          password: ${{ secrets.GMSAAS_PASSWORD }}
          recipe_uuid: 4c015ada-e64e-4f5d-a320-06cbf6e95648
